### PR TITLE
Add some new extraction options

### PR DESCRIPTION
**Pull request by NuSkooler**
* -o OUTDIR: supply output directory for extraction
* -l: line ending conversion
* list: optional list of file(s) to extract. defaults to all meeting existing criteria

### CODE REVIEW

**Comment by NuSkooler** [comment]
Kinda quick and dirty, so happy to make improvements if needed!

**Comment by NuSkooler** [comment]
FWIW, using this here: https://github.com/NuSkooler/enigma-bbs/commit/b6e7ecb193cf39ed33757b067a625ea439bf999c

**Comment by jhallen** [comment]
Thanks, I've taken your changes.  Cool BBS software!

**Comment by NuSkooler** [comment]
@jhallen Thanks!

**Pull request merged**
